FROM gmanka/archlinuxarm AS builder

RUN pacman -Syu git --noconfirm
RUN useradd -m user && echo "ALL ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers && pacman -S sudo base-devel --noconfirm
RUN cd /home/user && sudo -u user git clone https://github.com/hbiyik/agr.git && cd agr/ospackages/arch && sudo -u user makepkg -si --noconfirm
